#!/bin/bash

TMUXMANAGE_FILE=".tmuxmanage"

if [[ $1 == "setup" ]]; then

	if [ $# -lt 3 ]; then
    	echo "Usage: tmuxmanage setup [process name] [startup task]"
    	exit 1
	fi

	if [ -f "$TMUXMANAGE_FILE" ]; then
		echo "Cleaning up old .tmuxmanage file"
		rm -rf $TMUXMANAGE_FILE
	fi

	echo "Creating .tmuxmanage file"
	touch $TMUXMANAGE_FILE

	echo "Setting up tmuxmanage"
	echo $2 >> $TMUXMANAGE_FILE
	
	for task in "${@:3}"; do
		echo "$task" >> $TMUXMANAGE_FILE
	done

	echo "Finished setting up tmuxmanage!"
	exit

fi

if [ ! -f "$TMUXMANAGE_FILE" ]; then
    echo "Could not find .tmuxmanage file. Please run tmuxmanage setup [process name] [startup task]"
    exit
fi

PROCESS_NAME=$(head -n1 $TMUXMANAGE_FILE)


function start() {

	echo "Starting session"

	tmux new -d -s $PROCESS_NAME

	while read -r task; do

 		echo "Executing $task"

 		tmux send -t $PROCESS_NAME "$task" ENTER

	done <<< $(sed 1d $TMUXMANAGE_FILE)

	echo "Tmux session started! Connect with \"tmux a -t $PROCESS_NAME\" and disconnect with Ctrl B + D"

}

function stop() {

	echo "Stopping session"

	tmux kill-session -t $PROCESS_NAME

	echo "Tmux session stopped!"

}

if [[ $1 == "start" ]]; then

	start
	exit

elif [[ $1 == "stop" ]]; then

	stop
	exit

elif [[ $1 == "restart" ]]; then

	stop

	# tmux can "server exited unexpectedly" if ran too fast

	if [ $# -ge 2 ]; then
    	sleep $2
	else
		sleep 1
	fi

	start

	exit

fi
